### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by HiHoWillyO** [Fubukiyo/LabelPrinter#1]
This is what it should be

${
CT~~CD,~CC^~CT~
^XA~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR2,2~SD30^JUS^LRN^CI0^XZ
^XA
^MMT
^PW609
^LL0203
^LS-14
^BY2,3,50^FT85,150^BCN,,N,N
^fd>:1S^fs
^FT75,65^A0N,40,40^FH\^FD(1S)PN/SN:^fs
^PQ1,0,1,Y^XZ
}$

**Comment by Fubukiyo** [comment]
Formatting issue fixed.
